# This specifies the block bundle specs
# Uses the project's base image

bundle_name: readers
description: Blah
label: Reader Blocks
version: 0.1
image: my_custom_image:0.1 # if user has a custom image for the block bundle, it will be specified here.
libraries:
  - pandas>=1.3
  - opencsv==0.8
system_dependencies:
  - poppler
  - graphviz
environment:
  - TMP_FS_PATH: /opt/tmp
commands:
  - "cmd1"
  - "cmd2"
category: "Connectors.Source Connectors"
blocks:
  - name: csv_reader
    label: 'CSV Reader'
    classname: 'CSVReader'
    description: "..."
    executors:
      - ContainerExecutor # Resource specs would be available as part of the executors
      - SparkExecutor
    inputs:
      - name: inp1
        label: ""
        dtype: object # supported dtypes: object, array, integer, string, boolean, dynamic-list[integer/string/boolean/object/array], dynamic-object[integer/string/boolean/object/array]
        default_value: "{ }" # if the dtype is array or object, the default value will be a stringified value
        description: ""
        required: true
        type: series
      - name: inp2
        label: ""
        dtype: string
        default_value: "blah"
        description: ""
        required: true
        type: atomic
    outputs:
      - name: out1
        label: ""
        dtype: array
        default_value: "[ ]" # if the dtype is array or object, the default value will be a stringified value
        description: ""
        type: series
      - name: out2
        label: ""
        dtype: int
        default_value: 0
        description: ""
        type: atomic
    adapter:
    validator: