# This specifies the project config
name: Sample Project
description: This is a sample description
added_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
added_on: "2020-09-01 09:01:15"
updated_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
updated_on: "2020-09-01 09:01:15"
base_image: razor-core:2.2.1
base_os: ubuntu-20-lts
base_os_flavor: debian
base_image_config:
  pip_packages:
    - name: razor-flow
      version: 1.9
    - name: razor-fs
      version: 2.9
    - name: razor-ds
      version: 1.2
  system_packages:
    - name: poppler
    - name: graphviz
  environment_variables:
    - variable: TF_CONFIG
      type: String
      value: cluster_host:cluster_port
      desc: Desc regarding env variable
    - variable: PYSPARK_PYTHON
      type: String
      value: spark.python.driver
      desc: Desc regarding env variable
project_libraries:
  published_packages:
    - name: image_processing
      version: 0.2
      source: "marketplace"
      publisher: "tenant1" #this is the subdomain of the tenant who published the bundle
      added_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
      added_on: "2020-09-01 09:01:15"
      updated_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
      updated_on: "2020-09-01 09:01:15"
      pip_packages:
        - name: numpy
          version: 1.9
          added_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
          added_on: "2020-09-01 09:01:15"
          updated_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
          updated_on: "2020-09-01 09:01:15"
        - name: scipy
          version: 2.9
          added_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
          added_on: "2020-09-01 09:01:15"
          updated_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
          updated_on: "2020-09-01 09:01:15"
      system_packages:
        - name: poppler
          added_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
          added_on: "2020-09-01 09:01:15"
          updated_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
          updated_on: "2020-09-01 09:01:15"
        - name: graphviz
          added_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
          added_on: "2020-09-01 09:01:15"
          updated_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
          updated_on: "2020-09-01 09:01:15"
      environment_variables:
        - variable: TF_CONFIG
          type: String
          value: cluster_host:cluster_port
          desc: Desc regarding env variable
        - variable: PYSPARK_PYTHON
          type: String
          value: spark.python.driver
          desc: Desc regarding env variable
    - name: sentiment_analysis
      version: 1.1
      source: "tenantrepo"
      publisher: "tenant1" #this is the subdomain of the tenant who published the bundle
      added_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
      added_on: "2020-09-01 09:01:15"
      updated_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
      updated_on: "2020-09-01 09:01:15"
      pip_packages:
        - name: numpy
          version: 1.9
          added_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
          added_on: "2020-09-01 09:01:15"
          updated_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
          updated_on: "2020-09-01 09:01:15"
        - name: scipy
          version: 2.9
          added_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
          added_on: "2020-09-01 09:01:15"
          updated_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
          updated_on: "2020-09-01 09:01:15"
      system_packages:
        - name: poppler
          added_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
          added_on: "2020-09-01 09:01:15"
          updated_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
          updated_on: "2020-09-01 09:01:15"
        - name: graphviz
          added_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
          added_on: "2020-09-01 09:01:15"
          updated_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
          updated_on: "2020-09-01 09:01:15"
      environment_variables:
        - variable: TF_CONFIG
          type: String
          value: cluster_host:cluster_port
          desc: Desc regarding env variable
        - variable: PYSPARK_PYTHON
          type: String
          value: spark.python.driver
          desc: Desc regarding env variable
  pip_packages:
    - name: opencv
      version: 1.9
      user_uploaded: false
      added_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
      added_on: "2020-09-01 09:01:15"
      updated_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
      updated_on: "2020-09-01 09:01:15"
    - name: matplotlib
      version: 2.9
      user_uploaded: true # this means that the user has uploaded a whl file and that file would be pip_packages: installed
      added_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
      added_on: "2020-09-01 09:01:15"
      updated_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
      updated_on: "2020-09-01 09:01:15"
  system_packages:
    - name: default-jre-1.9
      added_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
      added_on: "2020-09-01 09:01:15"
      updated_by: 7b1dac56-5a40-4e9c-a204-aca62da1b145
      updated_on: "2020-09-01 09:01:15"
environment_variables:
  - variable: TF_CONFIG
    type: String
    value: cluster_host:cluster_port
    desc: Desc regarding env variable
  - variable: PYSPARK_PYTHON
    type: String
    value: spark.python.driver
    desc: Desc regarding env variable
additional_commands:
  - "mkdir /opt/app"
  - "chmod +x /opt/app/runapp.sh"
default_entrypoint: /opt/app/runapp.sh
