# This specifies the project config

project:

    # These are used to build the project’s default image - also used for Jupyter
    libraries:
        - pandas: 0.0.1
        - numpy: 0.1.3
        - razor: latest
    
    system-libraries:
        - poppler
        - graphviz

    marketplace-packages:
        - mybundle1
        - mybundle2