# This specifies the project config
base: razor-core:2.2.1
pip:
  - scikit-learn
  - opencv>=2.0.3
razor:
  - image_processing
  - spark_blocks>=2.0.3
  - spark_tf_blocks
  - graph_network
apt:
  - default-jre
build:
  mkdir /etc/libs
env:
  - TF_CONFIG="cluster-port:2555"
  - PYSPARK_DRIVER_PYTHON=spark.pyspark.driver.python
